 CREATE TABLE PROFESSOR (
         ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
         NOME VARCHAR(255) NOT NULL,
         EMAIL VARCHAR(255) NOT NULL,
         IDADE VARCHAR(255) NOT NULL,
         MATERIA VARCHAR(255) NOT NULL,
         TURNO VARCHAR(255) NOT NULL,
         SALARIO VARCHAR(255) NOT NULL,
         STATUS BOOL DEFAULT TRUE
     );

    SELECT * FROM PROFESSOR;
     //insert 
     INSERT INTO PROFESSOR (NOME) VALUES ("Guilherme");

    INSERT INTO PROFESSOR 